steps:
  - name: node:18.20.4
    entrypoint: yarn
    args: ["install"]
  - name: node:18.20.4
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:18.20.4
    entrypoint: yarn
    args: ["build"]
  - name: node:18.20.4
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]
